from datetime import datetime, timezone
from enum import Enum
from typing import List, Optional
from pydantic import BaseModel, Field, ConfigDict
from domain.states.recovery_state import RecoveryAction


class StrategyReasonCode(str, Enum):
    """
    Bounded, machine-readable reason codes explaining why a recovery strategy was selected.
    Arbitrary free-form strings are forbidden.
    """
    HISTORICAL_PAYMENT_WINDOW = "HISTORICAL_PAYMENT_WINDOW"
    TRANSIENT_PROVIDER_FAILURE = "TRANSIENT_PROVIDER_FAILURE"
    RAIL_DEGRADATION = "RAIL_DEGRADATION"
    INSUFFICIENT_FUNDS = "INSUFFICIENT_FUNDS"
    ACTIVE_ALTERNATIVE_MANDATE = "ACTIVE_ALTERNATIVE_MANDATE"
    MANDATE_INACTIVE = "MANDATE_INACTIVE"
    RETRY_LIMIT_APPROACHING = "RETRY_LIMIT_APPROACHING"
    HIGH_VALUE_CASE = "HIGH_VALUE_CASE"
    INSUFFICIENT_HISTORY = "INSUFFICIENT_HISTORY"
    UNKNOWN_FAILURE = "UNKNOWN_FAILURE"
    HUMAN_REVIEW_REQUIRED = "HUMAN_REVIEW_REQUIRED"


class PlannerSource(str, Enum):
    """Identifies the origin of a strategy proposal for auditability."""
    GEMINI_LLM = "GEMINI_LLM"
    DETERMINISTIC_FALLBACK = "DETERMINISTIC_FALLBACK"


class StrategyProposal(BaseModel):
    """
    Strongly typed, immutable strategy recommendation produced by the AI Strategy Planner
    or the Deterministic Fallback Planner.
    
    IMPORTANT: A StrategyProposal is purely ADVISORY. It does NOT authorize financial execution.
    Only the Policy Guardian can issue a PolicyAuthorization record.
    """
    model_config = ConfigDict(frozen=True)

    proposal_id: str = Field(..., description="Unique proposal ID (e.g. prop_8921)")
    recovery_case_id: str = Field(...)
    subscription_id: str = Field(...)
    action: RecoveryAction
    reason_codes: List[StrategyReasonCode] = Field(..., min_length=1)
    rationale: str = Field(..., min_length=5, description="Concise, human-readable rationale")
    strategy_confidence: Optional[float] = Field(
        default=None,
        ge=0.0,
        le=1.0,
        description="Model confidence in the recommendation when generated by an LLM; None for deterministic rule-based proposals.",
    )
    recommended_delay_seconds: int = Field(default=0, ge=0)
    recommended_retry_at: Optional[datetime] = None
    required_conditions: List[str] = Field(default_factory=list)
    planner_source: PlannerSource
    fallback_reason: Optional[str] = None
    generated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
